### ISSUE TITLE
Diagram not loaded properly in CS130 crib sheet

### ISSUE THREAD

**Issue by Linh012** [CSRG-Group/dcs-notes.github.io#151]
**Describe the bug**
In the CS130 crib sheet, the relation diagram under the Properties of relations section is missing.

**To Reproduce**
Go to the section: https://warwick.guide/modules/CS130/General_Crib_Sheet/#properties-of-relations

**Expected behavior**
Diagram is loaded properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/60060916/141503220-a5287f39-5581-4088-b156-27f14e34b707.png)

**Additional context**
I looked at the CS130 crib sheet source file and it seems that the image source is incorrect (refer to screenshot below). There is no media directory in the module CS130 directory.
![image](https://user-images.githubusercontent.com/60060916/141503679-b98736d4-3f5f-499f-af63-81c82d4191ad.png)

Additionally, for some reason, the diagram file can be found twice in the module CS118 directory.
![image](https://user-images.githubusercontent.com/60060916/141504667-4b5e600a-cc1a-4988-945d-3ff38fc5a6fa.png)

**Comment by LoudShadow** [comment]
Should be all sorted. Thanks for the detailed report.

**Comment by EdmundGoodman** [comment]
@all-contributors add @Linh012 to bugs
