### ISSUE TITLE
All-contributors bot does not edit the README.md file

### ISSUE THREAD

**Issue by EdmundGoodman** [CSRG-Group/dcs-notes.github.io#40]
When the all-contributors bot is used, it correctly creates a pull request and modifies its internal ".all-contributorsrc" json file, but does not change the README.md file, so the table of contributors cannot be seen in a meaningful way in the repo

**Comment by Justanhy** [comment]
This is a test: @all-contributors please add @Justanhy to design.

**Comment by Justanhy** [comment]
@all-contributors add @arkamnite to docs, content, maintenance
