### ISSUE TITLE
Text is no longer centered on non-content pages

### ISSUE THREAD

**Issue by EdmundGoodman** [CSRG-Group/dcs-notes.github.io#91]
**Describe the bug**
Text is no longer centered on non-content pages

**To Reproduce**
Go to a non-content page

**Expected behavior**
Text should be centered on non-content pages

**Screenshots**
Non-content page:
![image](https://user-images.githubusercontent.com/37504168/118526443-2878f780-b738-11eb-81dc-74b3ebb5d98c.png)

Content-page:
![image](https://user-images.githubusercontent.com/37504168/118526499-34fd5000-b738-11eb-89b3-77154d373f74.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by Justanhy** [comment]
Whoops thanks for spotting that
