### ISSUE TITLE
Equations are broken on the 126 page

### ISSUE THREAD

**Issue by Adrakaris** [CSRG-Group/dcs-notes.github.io#93]
On the one page notes: https://csrg-group.github.io/dcs-notes.github.io/CS126/opnotes

we have equations not rendering correctly:

![image](https://user-images.githubusercontent.com/17861497/118539597-83661b00-b747-11eb-8364-d23b872453ce.png)

**Comment by Justanhy** [comment]
I have included a temporary fix in c29faec, that should parse inline math blocks like S and D shown in the screenshot. Math blocks are parsed weirdly by kramdown when iterated through Jekyll collections (not sure if anyone reading this will know how to fix it). Will make an attempt when I have time.

**Comment by Justanhy** [comment]
67a71ce should fix the bug. I think using `markdownify` parses the content twice, so `\[` is parsed to `[`, so mathjax doesn't process it afterwards.
![image](https://user-images.githubusercontent.com/46620327/118625701-252a4e00-b7c2-11eb-8b95-75fb4ef577f2.png)
